jobs:
- ${{ each pythonVersion in parameters.pythonVersionsSupport }}:
  - job: ${{ format('Linux{0}Test', pythonVersion) }}

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      AZURECI: 1
      PYTHON_VERSION: ${{ pythonVersion }}
      ${{ if eq(pythonVersion, '3.6') }}:
        PYTHON_NO_DOT_VERSION: '36'
      ${{ if eq(pythonVersion, '3.7') }}:
        PYTHON_NO_DOT_VERSION: '37'
      ${{ if eq(pythonVersion, '3.8') }}:
        PYTHON_NO_DOT_VERSION: '38'

    strategy:
      matrix:
        bigquery:
          BACKENDS: 'bigquery'
        omniscidb:
          BACKENDS: 'omniscidb'

    steps:

      - bash: echo "${PYTHON_VERSION}"
        displayName: 'DISPLAY PYTHON VERSION'

      - bash: echo "${PYTHON_NO_DOT_VERSION}"
        displayName: 'DISPLAY PYTHON VERSION WITH NO DOT'

      - bash: echo "${BACKENDS}"
        displayName: 'DISPLAY BACKENDS'
