jobs:
- ${{ each pythonVersion in parameters.pythonVersionsSupport }}:
  - job: ${{ format('Linux{0}Test', pythonVersion) }}

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      AZURECI: 1
      PYTHON_VERSION: ${{ pythonVersion }}
      PYTHON_NO_DOT_VERSION: ${{ PYTHON_VERSION[0] }}${{ PYTHON_VERSION[2] }}

    strategy:
      matrix:
        bigquery:
          BACKENDS: 'bigquery'
        omniscidb:
          BACKENDS: 'omniscidb'

    steps:

      - bash: echo ${{ PYTHON_VERSION }}
        displayName: 'DISPLAY PYTHON VERSION'

      - bash: echo ${{ PYTHON_NO_DOT_VERSION }}
        displayName: 'DISPLAY PYTHON VERSION WITH NO DOT'

      - bash: echo ${{ BACKENDS }}
        displayName: 'DISPLAY BACKENDS'
