jobs:
- ${{ each PYTHON_VERSION in parameters.python_version_supports }}:
  - job: Linux${{ PYTHON_VERSION }}Test

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      AZURECI: 1
      PYTHON_VERSION: ${{ PYTHON_VERSION }}
      PYTHON_NO_DOT_VERSION: ${{ PYTHON_VERSION[0] }}${{ PYTHON_VERSION[2] }}

    strategy:
      matrix:
        bigquery:
          BACKENDS: 'bigquery'
        omniscidb:
          BACKENDS: 'omniscidb'

    steps:
    
      - bash: echo ${{ PYTHON_VERSION }}
        displayName: 'DISPLAY PYTHON VERSION'

      - bash: echo ${{ PYTHON_NO_DOT_VERSION }}
        displayName: 'DISPLAY PYTHON VERSION WITH NO DOT'

      - bash: echo ${{ BACKENDS }}
        displayName: 'DISPLAY BACKENDS'

