jobs:
- ${{ each pythonNoDotVersion in parameters.pythonNotDoVersionsSupport }}:
  - job: ${{ format('Linux{0}Test', pythonVersion) }}

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      AZURECI: 1
      PYTHON_NO_DOT_VERSION: ${{ pythonNoDotVersion }}
      ${{ if eq(pythonVersion, '36') }}:
        PYTHON_VERSION: '3.6'
      ${{ if eq(pythonVersion, '37') }}:
        PYTHON_VERSION: '3.7'
      ${{ if eq(pythonVersion, '38') }}:
        PYTHON_VERSION: '3.8'

    strategy:
      matrix:
        bigquery:
          BACKENDS: 'bigquery'
        omniscidb:
          BACKENDS: 'omniscidb'

    steps:

      - bash: echo "${PYTHON_VERSION}"
        displayName: 'DISPLAY PYTHON VERSION'

      - bash: echo "${PYTHON_NO_DOT_VERSION}"
        displayName: 'DISPLAY PYTHON VERSION WITH NO DOT'

      - bash: echo "${BACKENDS}"
        displayName: 'DISPLAY BACKENDS'
