jobs:

- template: azure-pipelines-linux.yml
  parameters:
          pythonVersionsSupport: [ { 'v': '3.6', 'vdot': '36' }, { 'v': '3.7', 'vdot': '37' }, { 'v': '3.8', 'vdot' } ]

- template: azure-pipelines-windows.yml
  parameters:
    pythonVersionsSupport: [ '3.6', '3.7', '3.8' ]
