jobs:

- template: azure-pipelines-linux.yml
  parameters:
    pythonVersionsSupport: [ '3.6', '3.7', '3.8' ]

- template: azure-pipelines-windows.yml
  parameters:
    pythonVersionsSupport: [ '3.6', '3.7', '3.8' ]
